### ISSUE TITLE
Access the miniImageNet dataset

### ISSUE THREAD

**Issue by Yuliang-Zou** [twitter/meta-learning-lstm#1]
Hi, I wonder how I can download the miniImageNet dataset. For some filenames in the csv file, I cannot find its corresponding url using the ImageNet api (this should return the (filename, url) pairs): http://www.image-net.org/api/text/imagenet.synset.geturls.getmapping?wnid=[wnid]. 

For example, "n0185567200000003.jpg" is the first one in val.csv, but when I replace the [wnid] with n01855672 to query the api, I cannot find any filename called "n01855672_3" or "n01855672_00000003". So I wonder if your filename is exactly the same as the original one in ImageNet. If not, can you tell me the mapping? Or can you upload the dataset somewhere and share it? Thanks!

**Comment by d1ngn1gefe1** [comment]
I am facing the same issue.

**Comment by songrotek** [comment]
So how to solve this problem?

**Comment by jongchyisu** [comment]
Same question here, how did you solve this?

**Comment by songrotek** [comment]
I sent an email to the author and he share his dataset for me

2017-09-30 3:10 GMT+08:00 Jong-Chyi Su <notifications@github.com>:

**Comment by niudong1001** [comment]
Facing same error, anybody knows how to download miniimagenet?
