### ISSUE TITLE
How to recover exact images from imagenet?

### ISSUE THREAD

**Issue by tsendeemts** [twitter/meta-learning-lstm#2]
Hi Sachin,

Great work!
I'm trying to recover the images for miniImagenet dataset you provided and can't seem to figure out.
I did notice that wordnet id is prefix of the fileids in the dataset. However, rest of the field doesn't seem to match the file names in imagenet.

I would really appreciate your help on this!

Thanks,
Tsendee

**Comment by TwoBranchDracaena** [comment]
Same question here.

**Comment by csyanbin** [comment]
It seems that some images are not in the imagenet2012 dataset.

**Comment by gitabcworld** [comment]
Hi Sachin! Great work. 

I am also having problem with the dataset. Maybe you have sorted the images by ID and name? If its like this could you provide the name of the first n0153282900000005.jpg in relation with ILSVRC 2012_img_train name. Just to know if the sort in ascending/descending order is correct.

If it is not like this, could you provide the correspondent relation between the ILSVRC 2012 and the IDs you have chosen for the train.csv, val.csv and test.csv?

**Comment by jongchyisu** [comment]
Same question here, how did you solve this?

**Comment by craklyn** [comment]
I also faced this problem and ultimately gave up on using this code.  Maybe tossing in a ping to @sachinravi14 will get some assistance.

**Comment by SinghGauravKumar** [comment]
@gitabcworld @tsendeemts @sachinravi14 did you guys solve it?

**Comment by dadashkarimi** [comment]
I have the same problem, could you find data?

**Comment by jshtok** [comment]
Hi, I have contacted Sachin Ravi at sachinr@Princeton.EDU. He gave me the link to the miniImageNet images and asked to tell people here to contact him for the link.

**Comment by ashwhall** [comment]
@jshtok I emailed Sachin at that email, but no response. Any chance you could pass on the link? ash.hall@latrobe.edu.au

**Comment by ErikYann** [comment]
@jshtok could you give the link ?

**Comment by ErikYann** [comment]
@jshtok  could you give the link ?

**Comment by ErikYann** [comment]
@jshtok could you give the link to me ?
