### ISSUE TITLE
./dataset/miniImagenet.lua:14: attempt to index local 'fid' (a nil value) stack traceback:

### ISSUE THREAD

**Issue by SeekPoint** [twitter/meta-learning-lstm#4]
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$ 
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$ th train/run-train.lua --task config.5-shot-5-class --data config.imagenet --model config.baselines.train-matching-net
Training with options:	{
  dataLoader : "dataset.data-loader"
  episodeSamplerKind : "permutation"
  dataName : "dataset.miniImagenet"
  nTest : 
    {
      1 : 100
      2 : 250
      3 : 600
    }
  batchSize : 75
  nDepth : 3
  nTrainShot : 5
  nIn : 84
  model : "config.baselines.train-matching-net"
  nTestShot : 
    {
      1 : 1
      2 : 5
    }
  useCUDA : true
  printPer : 1000
  rawDataDir : "data/miniImagenet/"
  useDropout : true
  test : "-"
  task : "config.5-shot-5-class"
  metaLearner : "model.baselines.matching-net"
  nEpisode : 75000
  embedModel : "model.baselines.simple-embedding"
  learningRate : 0.0001
  optimMethod : "adam"
  nValidationEpisode : 100
  steps : 3
  learner : "model.matching-net-classifier"
  nClasses : 
    {
      test : 5
      train : 5
      val : 5
    }
  nExamples : 20
  nEval : 15
  data : "config.imagenet"
}
Using data-loader: dataset.data-loader	
unzipping: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images.zip	
unzip:  cannot find or open /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images.zip, /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images.zip.zip or /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images.zip.ZIP.
data dir: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images	
/home/mldl/torch/install/bin/luajit: ./dataset/miniImagenet.lua:14: attempt to index local 'fid' (a nil value)
stack traceback:
	./dataset/miniImagenet.lua:14: in function 'loadSplit'
	./dataset/miniImagenet.lua:142: in function 'f'
	/home/mldl/torch/install/share/lua/5.1/moses.lua:104: in function 'each'
	./dataset/miniImagenet.lua:140: in function <./dataset/miniImagenet.lua:111>
	./dataset/data-loader.lua:34: in function <./dataset/data-loader.lua:13>
	./train/train.lua:26: in function <./train/train.lua:6>
	train/run-train.lua:16: in main chunk
	[C]: in function 'dofile'
	...mldl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$

**Comment by dragen1860** [comment]
Hi, you should download images.zip file and copy it into meta-learning-lstm/data/miniImagenet/miniImagenet/images.zip location.
images.zip is the mini-imagenet dataset, which is not public downloadable but I have.

**Comment by SeekPoint** [comment]
so , would you like share this file to me?

**Comment by dragen1860** [comment]
send me an email : dcslong@nus.edu.sg

**Comment by SeekPoint** [comment]
I moves but got the error:

  inflating: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images/n1313361300001297.jpg  
  inflating: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images/n1313361300001299.jpg  
data dir: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images	
/home/mldl/torch/install/bin/luajit: ./dataset/miniImagenet.lua:14: attempt to index local 'fid' (a nil value)
stack traceback:
	./dataset/miniImagenet.lua:14: in function 'loadSplit'
	./dataset/miniImagenet.lua:142: in function 'f'
	/home/mldl/torch/install/share/lua/5.1/moses.lua:104: in function 'each'
	./dataset/miniImagenet.lua:140: in function <./dataset/miniImagenet.lua:111>
	./dataset/data-loader.lua:34: in function <./dataset/data-loader.lua:13>
	./train/train.lua:26: in function <./train/train.lua:6>
	train/run-train.lua:16: in main chunk
	[C]: in function 'dofile'
	...mldl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$ 

my tree show:


mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$ tree
.
├── config
│   ├── 1-shot-5-class.lua
│   ├── 5-shot-5-class.lua
│   ├── baselines
│   │   ├── init.lua
│   │   ├── test-conv-nearest-neighbor.lua
│   │   ├── test-matching-net.lua
│   │   ├── train-conv-nearest-neighbor.lua
│   │   ├── train-matching-net.lua
│   │   ├── train-pixel-nearest-neighbor.lua
│   │   └── train-pre-trained-SGD.lua
│   ├── imagenet.lua
│   ├── init.lua
│   └── lstm
│       ├── init.lua
│       ├── test-lstm.lua
│       ├── train-imagenet-1shot.lua
│       └── train-imagenet-5shot.lua
├── data
│   └── miniImagenet
│       ├── miniImagenet
│       │   └── images.zip
│       ├── test.csv
│       ├── train.csv
│       └── val.csv
├── dataset
│   ├── data-loader.lua
│   ├── dataset.lua
│   ├── init.lua
│   └── miniImagenet.lua
├── LICENSE
├── luarocks_install_Dataset
├── model
│   ├── baselines
│   │   ├── conv-nearest-neighbor.lua
│   │   ├── FCE-embedding.lua
│   │   ├── garbage
│   │   │   └── matching-net-test.lua
│   │   ├── init.lua
│   │   ├── matching-net.lua
│   │   ├── nearest-neighbor.lua
│   │   ├── pixel-nearest-neighbor.lua
│   │   ├── pre-trained-SGD.lua
│   │   ├── pre-train.lua
│   │   └── simple-embedding.lua
│   ├── init.lua
│   ├── lstm
│   │   ├── init.lua
│   │   ├── lstm-helper.lua
│   │   ├── meta-learner-lstm.lua
│   │   ├── RecurrentLSTMNetwork.lua
│   │   └── train-lstm.lua
│   ├── lstm-classifier.lua
│   └── matching-net-classifier.lua
├── README.md
├── torch-dataset
│   ├── CMakeLists.txt
│   ├── dataset-scm-1.rockspec
│   ├── examples
│   │   ├── cifar10.lua
│   │   └── mnist.lua
│   ├── LICENSE
│   ├── lua
│   │   ├── Batch.lua
│   │   ├── Cache.lua
│   │   ├── Dataset.lua
│   │   ├── Getters.lua
│   │   ├── IndexCSV.lua
│   │   ├── IndexDirectory.lua
│   │   ├── Index.lua
│   │   ├── IndexSlowFS.lua
│   │   ├── IndexTensor.lua
│   │   ├── IndexUtils.lua
│   │   ├── Reader.lua
│   │   ├── Sampler.lua
│   │   ├── SlowFS.lua
│   │   ├── SlowFSStream.lua
│   │   └── StreamedDataset.lua
│   ├── README.md
│   ├── src
│   │   ├── dataset.c
│   │   └── error.h
│   └── test
│       ├── files
│       │   ├── 1.txt
│       │   ├── 2.txt
│       │   ├── 3.txt
│       │   └── local
│       │       ├── cats
│       │       │   ├── cat1.txt
│       │       │   └── cat2.txt
│       │       ├── dogs
│       │       │   └── dog1.txt
│       │       ├── unlabeled1.txt
│       │       └── unlabeled2.txt
│       ├── hdfs
│       │   ├── blockreader
│       │   └── files
│       │       ├── part-r-00000
│       │       ├── part-r-00001
│       │       ├── part-r-00002
│       │       └── part-r-00003
│       ├── index1.csv
│       ├── index2.csv
│       ├── index2-meta.csv
│       ├── index3.csv
│       ├── index4.csv
│       ├── index.csv
│       ├── index-files.csv
│       ├── nolabels.csv
│       ├── test_Cache.lua
│       ├── test_Dataset.lua
│       ├── test_Getters.lua
│       ├── test_Index.lua
│       ├── test.lua
│       ├── test_offsets.lua
│       ├── test_Reader.lua
│       ├── test_Sampler.lua
│       ├── test_StreamedDataset.lua
│       └── TestUtils.lua
├── train
│   ├── init.lua
│   ├── run-train.lua
│   └── train.lua
├── util
│   ├── init.lua
│   └── util.lua
├── visualize
│   ├── init.lua
│   ├── plot_all.py
│   ├── plot_gate_vals.py
│   ├── plot_loss.py
│   ├── plot_params.py
│   ├── plot_sgd.py
│   ├── plot_validation.py
│   ├── visualize_gates.lua
│   └── visualize_weights.lua
└── yknote---

25 directories, 113 files
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$

**Comment by SeekPoint** [comment]
after move *. csv to data/miniImagenet/miniImagenet

this error disappear, but got another one:


mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$ th train/run-train.lua --task config.5-shot-5-class --data config.imagenet --model config.baselines.train-matching-net
Training with options:	{
  dataLoader : "dataset.data-loader"
  episodeSamplerKind : "permutation"
  dataName : "dataset.miniImagenet"
  nTest : 
    {
      1 : 100
      2 : 250
      3 : 600
    }
  batchSize : 75
  nDepth : 3
  nTrainShot : 5
  nIn : 84
  model : "config.baselines.train-matching-net"
  nTestShot : 
    {
      1 : 1
      2 : 5
    }
  useCUDA : true
  printPer : 1000
  rawDataDir : "data/miniImagenet/"
  useDropout : true
  test : "-"
  task : "config.5-shot-5-class"
  metaLearner : "model.baselines.matching-net"
  nEpisode : 75000
  embedModel : "model.baselines.simple-embedding"
  learningRate : 0.0001
  optimMethod : "adam"
  nValidationEpisode : 100
  steps : 3
  learner : "model.matching-net-classifier"
  nClasses : 
    {
      test : 5
      train : 5
      val : 5
    }
  nExamples : 20
  nEval : 15
  data : "config.imagenet"
}
Using data-loader: dataset.data-loader	
data dir: /home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/images	
splitfile is	/home/mldl/ub16_prj/meta-learning-lstm/data/miniImagenet/miniImagenet/train.csv	
/home/mldl/torch/install/bin/luajit: /home/mldl/torch/install/share/lua/5.1/dataset/Reader.lua:52: Attempt to serialize closure './dataset/miniImagenet.lua:32' with 1 upvalues; first is: '_'.
Consider using ipc.workqueue.writeup() instead.
stack traceback:
	[C]: in function 'map'
	/home/mldl/torch/install/share/lua/5.1/dataset/Reader.lua:52: in function 'Reader'
	/home/mldl/torch/install/share/lua/5.1/dataset/Dataset.lua:71: in function 'sampledBatcher'
	./dataset/miniImagenet.lua:148: in function 'f'
	/home/mldl/torch/install/share/lua/5.1/moses.lua:104: in function 'each'
	./dataset/miniImagenet.lua:141: in function <./dataset/miniImagenet.lua:112>
	./dataset/data-loader.lua:34: in function <./dataset/data-loader.lua:13>
	./train/train.lua:26: in function <./train/train.lua:6>
	train/run-train.lua:16: in main chunk
	[C]: in function 'dofile'
	...mldl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
mldl@mldlUB1604:~/ub16_prj/meta-learning-lstm$

**Comment by ajeetksingh** [comment]
Hi @loveJasmine did you solve the above problem? Right now I am stuck at the same (striked through lines) juncture as you were.
Can you please suggest the solution which worked for you. Thank you.

**Comment by SeekPoint** [comment]
@ajeetksingh 

you should contact @dragen1860 to get a data file

**Comment by ajeetksingh** [comment]
@loveJasmine 

Thanks for the swift response. But, I don't have a problem with the data file. I have create my own and have kept at the appropriate classes. I am facing this problem while running at following exact location:  

`/home/mldl/torch/install/bin/luajit: /home/mldl/torch/install/share/lua/5.1/dataset/Reader.lua:52: Attempt to serialize closure './dataset/miniImagenet.lua:32' with 1 upvalues; first is: '_'.`

What did you do to solve this? Was data file from @dragen1860 solved it? Or was there something else?

Thanks. :)

**Comment by dragen1860** [comment]
@ajeetksingh I don't solve the problem about `Attempt to serialize closure `. I spent several days to find out the solution. unfortunately, it remains. I contacted the author by email, but he seems no reply yet. Wish you can find some approach .

**Comment by ErikYann** [comment]
@loveJasmine could you please tell me where is the  *. csv ? I have a problem as"attempt to index local 'fid' (a nil value)"

**Comment by ErikYann** [comment]
@loveJasmine Did you solve the above problem at present? Right now I am stuck at the same juncture as you were.
//Attempt to serialize closure './dataset/miniImagenet.lua:31' with 1 upvalues; first is: '_'.

**Comment by d-li14** [comment]
@loveJasmine @dragen1860 How did you organize the directory structure? I have moved the *.csv to `data/miniImagenet/miniImagenet` but still got the same error "./dataset/miniImagenet.lua:14: attempt to index local 'fid' (a nil value)".
My data folder looks like this
```shell
data
└── miniImagenet
    └── miniImagenet
        ├── images
        ├── images.zip
        ├── test.csv
        ├── train.csv
        └── val.csv
```
Thanks.
