### ISSUE TITLE
Attempt to serialize closure './dataset/miniImagenet.lua:31' with 1 upvalues

### ISSUE THREAD

**Issue by dragen1860** [twitter/meta-learning-lstm#5]
`/home/i/torch/install/bin/luajit: /home/i/torch/install/share/lua/5.1/dataset/Reader.lua:52: Attempt to serialize closure './dataset/miniImagenet.lua:31' with 1 upvalues; first is: '_'.
Consider using ipc.workqueue.writeup() instead.`

What wrong?

**Comment by SeekPoint** [comment]
I reach the same error

**Comment by dragen1860** [comment]
Yes, maybe this is a problem of torch-ipc. But anyone can provides any help?

**Comment by abdullahjamal** [comment]
Has anyone able to figure out the problem? I've got the same error.
/home/yang/torch/install/bin/lua: /home/yang/torch/install/share/lua/5.2/dataset/Reader.lua:52: Attempt to serialize closure './dataset/miniImagenet.lua:31' with 2 upvalues; first is: '_ENV'.
Consider using ipc.workqueue.writeup() instead.

**Comment by dragen1860** [comment]
I think the algorithm has been abandoned, since it's novel but not promising. 
and nobody care about the bugs in the source project.

**Comment by sachinravi14** [comment]
Hi, unfortunately I'm not actively working in torch anymore so I'm not sure of the solution off the top of my head. I would suggest making sure you have the right version of torch-ipc as stated in the README.

**Comment by abdullahjamal** [comment]
@sachinravi14 I'm using LUA 5.2, I just want to make sure which version of LUA did you use? Does it has any effect?

**Comment by abdullahjamal** [comment]
So, I have installed torch again with LUA 5.1. Then I download the right version of torch-ipc as stated in the README, and run luarocks make in the torch-ipc folder. I also run luarocks make for torch-dataset. Now, the "code is running without any error".

**Comment by ErikYann** [comment]
@abdullahjamal could you please tell me how to download the right version of torch-ipc ?

**Comment by abdullahjamal** [comment]
It is stated in description. You can go to this commit 'c1b2984c4c2dae085005d385996f4c0660173b27'
