### ISSUE TITLE
miniimagenet access?

### ISSUE THREAD

**Issue by samaonline** [twitter/meta-learning-lstm#6]
Hi, I was wondering where I can download the mini_imagenet dataset used in your paper? thanks.

**Comment by dragen1860** [comment]
I have the dataset

**Comment by samaonline** [comment]
Hi @dragen1860 , thanks so much for your reply! I really need this dataset for my experiments... Could you please share the link of the dataset, or send me it via email (samaonline @ live.com)? Thanks again!

**Comment by dragen1860** [comment]
sent already

**Comment by samaonline** [comment]
Got it! Thank you so much!!

**Comment by tachim** [comment]
@dragen1860 can you please email it to me as well? tachim@cs.stanford.edu.

**Comment by dragen1860** [comment]
@tachim sent already.

**Comment by dongzhuoyao** [comment]
maybe this [https://github.com/renmengye/few-shot-ssl-public](https://github.com/renmengye/few-shot-ssl-public)

**Comment by ashaw596** [comment]
@dragen1860 Sorry to bump the thread. Do you happen to still have a copy of the mini-imagenet files? Could you send it to me at ashaw596@gatech.edu ? Thanks so much!!

**Comment by anindyasarkarIITH** [comment]
@dragen1860 can you please email it to me as well? anindyasarkar.ece@gmail.com

**Comment by tch24900** [comment]
Hi @dragen1860 , I would also like to receive a copy of this dataset if you could make it available to me.  My email is tch24900@ucmo.edu .  Thank you!

**Comment by ckghosted** [comment]
Hi @dragen1860 , would you please also email the dataset to me at ckghosted@gmail.com ? Thank you!

**Comment by flexibility2** [comment]
Hi @dragen1860 , would you please also email the dataset to me at 729406307@qq.com ? Thank you!

**Comment by dragen1860** [comment]
hi, all. Please download from here: https://drive.google.com/open?id=1HkgrkAwukzEZA0TpO7010PkAOREb2Nuk

**Comment by chenjie** [comment]
@dragen1860 Thank you.

**Comment by dragen1860** [comment]
It seems like miniImageNet dataset is copyright reserved. Please dnt distribute this dataset at liberty.

**Comment by sachinravi14** [comment]
Please email me at sachinr@princeton.edu and I can share the dataset with you.

**Comment by zizhao** [comment]
@dragen1860 can you please email it to me as well? zizhaowu@gmail.com

**Comment by dragen1860** [comment]
@zizhao  Sent alr. Please contact @sachinravi14  for mini-imagenet download. He is the author. ^-^

**Comment by KaminLee** [comment]
@dragen1860 can you please email it to me as well? kamin1130@gmail.com

**Comment by AristotelisPap** [comment]
Could you please send it to me as well? aristotelis.a.papadopoulos@gmail.com

**Comment by abhoi** [comment]
Can I get access to the dataset as well? amlaab@gmail.com

**Comment by getterk96** [comment]
@dragen1860 @sachinravi14 Thank you for your contribution! I would appreciate it if you could share the dataset with me, and I have already sent a email to @sachinravi14 . Here is my email address: gaojh15@mails.tsinghua.edu.cn

**Comment by jingjingjing-666** [comment]
@dragen1860 can you send is to me as well please? My email address: ucabhji@ucl.ac.uk

**Comment by zdaiot** [comment]
@dragen1860 Is it convenient for you to send me a copy? zdaiot@163.com

**Comment by felixshiyong** [comment]
@dragen1860 can I also have the miniimageNet dataset? My email address is: felixshiyong@jhmi.edu

**Comment by zdaiot** [comment]
@dragen1860 can you send is to me as well please? My email address:zdaiot@163.com

**Comment by leon-liangwu** [comment]
@dragen1860  Could you please kindly send me the data? Thanks very much. 
my email:  leon.liangwu@gmail.com

**Comment by anagha-ana** [comment]
hi @dragen1860  can you please forward me the mini-imagenet dataset ? I require it for testing my project

**Comment by ghost** [comment]
hi @dragen1860 can you please forward me the mini-imagenet dataset at animbekar25@gmail.com ? I require it for testing my project

**Comment by xue19890510** [comment]
hi, @sachinravi14 , @dragen1860  my email address is 302702579@qq.com, could you send me the data link? thank you very much

**Comment by DongSky** [comment]
> It seems like miniImageNet dataset is copyright reserved. Please dnt distribute this dataset at liberty.

hi @dragen1860 can you please forward me the mini-imagenet dataset at cndongsky@gmail.com ? I require it for testing my model
